email:
  template: "matrix-appservice-email+%KEY%@kamax.io"

  receiver:
    type: "imaps"
    host: "imap.kamax.io"
    port: 993
    login: "matrix-appservice-email@kamax.io"
    password: "matrix-appservice-email"

  sender:
    host: "smtp.kamax.io"
    port: 587
    tls: 1
    login: "matrix-appservice-email@kamax.io"
    password: "matrix-appservice-email"
    email: "matrix-appservice-email@kamax.io"
    name: "Matrix E-mail Bridge"
