# Basic Spring/embedded HTTP server configuration
server:

  # HTTP Port to listen to by default
  port: 8091


# Matrix side configuration
matrix:

  # Domain that this AS belongs to. Used in a various place when generating/validating Matrix IDs.
  # This value is typically the same as your HS domain.
  domain: "localhost"

  # Homeserver configuration
  home:

    # HS Client endpoint address
    host: "http://localhost:8008"

    # The token used by the AS when communicating with the HS
    # On *Nix-based system, running the following command is a good start point: pwgen 64 1
    asToken: "MY_SECRET_AS_TOKEN_CHANGE_ME"

    # The token used by the HS when communicating with the AS
    # On *Nix-based system, running the following command is a good start point: pwgen 64 1
    hsToken: "MY_SECRET_HS_TOKEN_CHANGE_ME"

    # The localpart of the AS global user. The domain will always be the one of the HS
    localpart: "appservice-email"

    # A list of localpart templates used to generate virtual MXID and produce a regexp for the HS config.
    users:
        # Values that will be replaced:
        #
        # %EMAIL%   Replaced by the full e-mail address, after doing a transform on the invalid MXID characters
      - template: "email_%EMAIL%"

  # Identity server configuration
  identity:

    # Locapart template to use when generating virtual users.
    # This should be the same value as the main template config item in the users users config section.
    #
    # Supported token:
    #   %EMAIL%     Replaced by an identifier representing the e-mail address
    template: "email_%EMAIL%"


# E-mail side configuration
email:

  # E-mail receiver configuration, from where the e-mail will be read to be injected into Matrix
  receiver:

    # Type of connector
    # Supported values:
    #  - imaps
    #  - imap
    #  - pop3
    type: "imap"

    # Hostname/IP of the e-mail server
    host: "localhost"

    # Port to connect to, mandatory
    port: 143

    # Username for the connection
    login: "matrix-appservice-email"

    # Password for the connection
    password: "CHANGE_ME"

    # E-mail template to use to identity which subscription the message belongs to, for individual user subscriptions.
    # This will typically be used in:
    #  - the 'Reply-To:' header in outgoing e-mail
    #
    # Variables that will be replaced:
    #  - %KEY%    Subscription ID that uniquely identity a bridge user in a room
    email: "matrix-appservice-email+%KEY%@localhost"

  # E-mail sender configuration, from where the e-mail will be sent when bridging events from Matrix
  # SMTP is the only supported protocol
  sender:

    # Hostname/IP of the e-mail server
    host: "localhost"

    # Port to connect to, mandatory
    port: 587

    # TLS mode for the connection.
    # Possible values:
    #  0    Disable TLS entirely
    #  1    Enable TLS if supported by server
    #  2    Force TLS and fail if not available
    tls: 1

    # Username for the connection
    login: "matrix-appservice-email"

    # Password for the connection
    password: "CHANGE_ME"

    # E-mail address to use in the 'From:' header
    email: "matrix-appservice-email@localhost"

    # Default display name to use in the 'From:' header
    # This will typically only be used if the user that triggered a notification is the same as the receiver.
    # Else, the sender display name will be used, e.g. if a Matrix user sends a message to an e-mail user.
    #
    # An empty value will only set the e-mail in the header
    name: "Matrix E-mail Bridge"


# Subscription management
subscription:

  # Public subscription portal where e-mail users can manage their subscriptions
  portal:

    # URL that should be included in notifications. This should be a publicly reachable address
    url: "https://my.public.domain.example.org"

  # Persistence storage configuration for subscriptions
  # Currently supported storages:
  #   - SQLite
  storage:

    # SQLite configuration
    sqlite:

      # Where the SQLite DB file should be located
      location: "as-subscriptions.db"

  # Global configuration for notifications
  #
  # Notifications can be configured per side of the bridge (e-mail or matrix) and per event.
  # List of supported events:
  # - onCreate    When a new subscription is created. Currently, only when a Matrix user invites an E-mail virtual user to a room.
  # - onMessage   When a message is sent to a Matrix room. This is triggered for both Matrix and E-mail users.
  # - onDestroy   When a subscription is destroyed, either by kicking a virtual user from the room, or by cancelling a subscription from the portal.
  notification:

    # E-mail notifications configuration
    #
    # E-mail notifications are composed of a subject and content.
    # subject is a string configuration property
    # content is an array of properties, each content mapping to an e-mail Part.
    #
    # content properties:
    # - type      MIME type for the content. This will be matched, if possible, to the content type(s) from either side of the bridge.
    # - header    Path to the header template file that can be shared across templates. If empty, will not be included.
    # - footer    Path to the footer template file that can be shared across templates. If empty, will not be included.
    # - content   Path to the content template file. Must be set
    #
    # Subject and content can contain various placeholder tokens that will be replaced when creating the notification itself.
    # Tokens that can be used in templates:
    # - %MSG_CONTENT%         Content, if applicable, that comes with the event. e.g. onMessage event will have this
    #                         token contain the actual message sent
    #
    # - %MSG_TIME_HOUR%       Hour at which the event was triggered or message sent, in 24H format with leading 0
    #
    # - %MSG_TIME_MIN%        Minutes at which the event was triggered or message sent, with leading 0
    #
    # - %MSG_TIME_SEC%        Seconds at which the event was triggered or message sent, with leading 0
    #
    # - %SENDER%              Best available display name for the event source/message sender
    #                         This would translate to the Matrix display name or, if not available, to the Matrix ID
    #
    # - %SENDER_NAME%         Source/Sender display name, empty if none is set
    #
    # - %SENDER_ADDRESS%      Source/Sender address, always populated
    #
    # - %SENDER_AVATAR%       Attachment ID for the Source/Sender avatar/icon. This can be used in HTML templates:
    #                         <img id="%SENDER_AVATAR%" src="cid:%SENDER_AVATAR%"> would include the avatar
    #
    # - %RECEIVER_ADDRESS%    Address of the notification receiver. Typically set to the e-mail address of the user
    #
    # - %ROOM%                Best available display name of the Matrix room to which the subscription is linked
    #                         This would translate to the Matrix display name or, if not available, to the Matrix ID
    #
    # - %ROOM_NAME%           Room display name, empty if none is set
    #
    # - %ROOM_ADDRESS%        Room address, always populated
    #
    # - %MANAGE_URL%          URL to the subscription management portal page of the user
    #
    email:
      onCreate:
          subject: "%SENDER% invited you to a new Matrix conversation"
          content:
          - type: "text/plain"
            header: "classpath:templates/email/header.txt"
            footer: "classpath:templates/email/footer.txt"
            content: "classpath:templates/email/onSubCreate-content.txt"

          - type: "text/html"
            header: "classpath:templates/email/header.html"
            footer: "classpath:templates/email/footer.html"
            content: "classpath:templates/email/onSubCreate-content.html"

      onDestroy:
        subject: "Matrix conversation in room %ROOM% has been terminated"
        content:
          - type: "text/plain"
            header: "classpath:templates/email/header.txt"
            footer: "classpath:templates/email/footer.txt"
            content: "classpath:templates/email/onSubDestroy-content.txt"

          - type: "text/html"
            header: "classpath:templates/email/header.html"
            footer: "classpath:templates/email/footer.html"
            content: "classpath:templates/email/onSubDestroy-content.html"

      onMessage:
        subject: "%SENDER% sent you a message on Matrix"
        content:
          - type: "text/plain"
            header: "classpath:templates/email/header.txt"
            footer: "classpath:templates/email/footer.txt"
            content: "classpath:templates/email/onSubMessage-content.txt"

          - type: "text/html"
            header: "classpath:templates/email/header.html"
            footer: "classpath:templates/email/footer.html"
            content: "classpath:templates/email/onSubMessage-content.html"

    # Only boolean values
    matrix:
      # 'onCreate' and 'onMessage' are not supported here
      onDestroy: true

# Bridge configuration
bridge:

  command:
    # Keyword trigger used to send command to the AS via Matrix, in rooms where the AS user is present
    keyword: "!email"

  invite:
    # List of Matrix user domains which are allowed to invite virtual users within a room.
    # This is useful to prevent federated invite and control spam so only users of given HS can create new subscriptions.
    domain: []

# Logging configuration
logging:

  # Change the log location to whatever you want here. Leave empty or comment out to disable
  file: "mxasd-email.log"
  level:
    org:
      springframework: "WARN"
      apache:
        catalina: "WARN"
